tanghaibao/jcvi

compara/synteny.py, graphics/karyotype.py
First change for plot whiskers above. Layout file can be same as before when 'above' is not needed.
Second change for error hint.
=> Code changes in karyotype.py and synteny.py

apps/tesseract.py, graphics/grabseeds.py
use PIL package to load Image module
change skimage.filter to skimage.filters
=> changes in modules

jcvi/annotation/train.py
Refer to https://github.com/tanghaibao/jcvi/issues/150
=> Improvement in jcvi.annotation.train augustus

jcvi/graphics/grabseeds.py
import exception with canny being a feature, not a filter. main change adds a method to change the background color in the source image to a specified color, default is blue, for contrast versus the seed color. this is to improve detection of seeds.
=> fix import exception, add logic to transform background color

jcvi/graphics/grabseeds.py
Adds function and option to change the background color by scanning the pixels (skipping black), and then converting pixels that fit within a set range of the average color to a chosen color.
=> grabseeds add function

.github/workflows/build.yml, jcvi/apps/fetch.py, jcvi/graphics/karyotype.py, jcvi/graphics/synteny.py
Add option `--shadestyle` to choose between `curve` (default) and `line` styles for syntenic wedges (thanks @LHXqwq)
=> Shadestyle (#185)

jcvi/__init__.py, jcvi/assembly/kmer.py, jcvi/graphics/base.py
Adding method 'nbinom' in kmer analysis, in addition to the 'allpaths' code. The 'nbinom' code is more accurate on heterozygous or polyploid genome surveys.  Although both are modeling the negative binomial distributions. This implementation is separate from the GenomeScope implementation and uses different numerical optimization schemes.
=> Assembly kmer histogram

jcvi/graphics/synteny.py
A commonly requested feature. Add gene name on the synteny plot.
=> Add gene id on local synteny (thanks: #209 @guosongjia, #256 @Tong-chen)

jcvi/formats/paf.py
Add parsing of PAF file format and conversion to BED.
See also:
https://github.com/lh3/miniasm/blob/master/PAF.md
=> [formats] Add paf

jcvi/graphics/grabseeds.py
vq error for float boxsize number.
=> float box size handling

docker/jcvi.dockerfile, jcvi/apps/base.py, jcvi/apps/fetch.py, tests/apps/test_fetch.py
=> [docker] Install curl in docker; add warnings in get_cookies() per #307

jcvi/assembly/geneticmap.py
Address issue in #317 by adding the option to allow other delimiters
=> [assembly] Add option --sep in geneticmap.bed() (#317, thanks @hungweichen0327)

.github/workflows/build.yml, .pylintrc, jcvi/graphics/synteny.py, requirements.txt, setup.py, setup_helper.py
Remove pytest* from `requirements.txt` so users who don't need testing won't have to install these packages.
=> [setup] Add tests_require

jcvi/annotation/reformat.py, jcvi/apps/base.py, jcvi/apps/console.py, jcvi/formats/agp.py, jcvi/formats/fastq.py, jcvi/graphics/base.py, jcvi/graphics/karyotype.py
Most warnings were due to quote as raw strings in `re.compile`
=> Suppress test warnings

jcvi/assembly/allmaps.py
ALLMAPS (via `liftOver`) may fail due to integer overflow.
Add option `--crossmap` to use to support use of alternative lift over tool.
=> Support CrossMap in ALLMAPS (thanks @RNieuwenhuis, #522)

jcvi/compara/catalog.py, jcvi/formats/blast.py
A recent regression occurred that failed to produce consistent file names for filtered BLAST files. This is a potential fix.
=> Fix self BLAST naming issue with float (thanks @AzumaSerenThePatriot,@dwpeng, #567)

jcvi/apps/base.py
=> replace logging's debug function

pyproject.toml
old licence format deprecated.
@tanghaibao please check licence name is appropriate.
=> update licence format

pyproject.toml, src/jcvi/graphics/ribbon.py
Update add_option method to add_argument.
Restore missing opt --extra-annotation to plot secondary anntation track.
Add debug logs
=> Ribbon Fixes

.github/workflows/pytest.yml, .vscode/extensions.json, .vscode/settings.json, README.md, pyproject.toml, src/jcvi/graphics/ribbon.py, tests/assembly/test_allmaps.py
Add option to ribbon module to plot bed annotations at boxes to highlight a region,
=> ribbon_annot_boxes

src/jcvi/compara/synteny.py, src/jcvi/graphics/ribbon.py
support colour codes beginning with # in blocks file
=> ribbon_patch
