assembly/allmaps.py
The error occurred because ALLMAPS supports only 8 color and hence index error.
Traceback (most recent call last):
File "/home/wyim/bin/python2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/home/wyim/bin/python2.7/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/assembly/allmaps.py", line 1725, in <module>
main()
File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/assembly/allmaps.py", line 824, in main
p.dispatch(globals())
File "/data/wyim/won/bin/jcvi/jcvi_env/lib/python2.7/site-packages/jcvi-0.6.6-py2.7.egg/jcvi/apps/base.py", line 82, in dispatch …
=> more than 8 map in ALLMAPS, color Palette error

apps/align.py, compara/catalog.py
In some situations, users want to perform synteny analysis using protein sequences instead of CDS. I added  the argument `--dbtype` for LAST in jcvi.apps.align and ortholog in jcvi.compara.catalog. The argument could simplify the procedure, although the function can be achieved by running LAST or BLASTP separately and specifying the output filename as "query.subject.last".
Here is an example of *Glycine max* vs *Medicago truncatula*:
```
$ python -m jcvi.compara.catalog ortholog Gm Mt --dbtype=prot
grep '^###' Gm.Mt.anchors -c # 1,434 blocks
grep -v '^###' Gm.Mt.anchors -c # 40,013 anchors
```
```
$ python -m jcvi.compara.catalog ortholog Gm Mt
grep '^###' Gm.Mt.anchors -c # 1,305 blocks
grep -v '^###' Gm.Mt.anchors -c # 36,352 anchors
```
Similar result but higher numbers of anchors and …
=> add the argument --dbtype for LAST (jcvi.apps.align) and ortholog (jcvi.compara.catalog)

compara/synteny.py
Print a friendly error message when no anchor are found.
```
11:03:27 [synteny] Assuming --qbed=Tva.bed --sbed=Pkn.bed
11:03:27 [base] Load file `Tva.bed`
11:03:28 [base] Load file `Pkn.bed`
11:03:28 [base] Load file `Tva.Pkn.last.filtered`
11:03:28 [synteny] A total of 6268 BLAST imported from `Tva.Pkn.last.filtered`.
11:03:28 [synteny] Chaining distance = 20
11:03:28 [base] Load file `Tva.Pkn.anchors`
11:03:28 [synteny] A total of 0 anchor was found. Aborted.
Traceback (most recent call last):
File "/data/software/python27/lib/python2.7/runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/data/software/python27/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/data/software/jcvi/compara/catalog.py", line 825, in <module> …
```
=> raise error while no anchor found

__main__.py, algorithms/__main__.py, annotation/__main__.py, apps/__main__.py, apps/base.py, assembly/__main__.py, compara/__main__.py, formats/__main__.py, graphics/__main__.py, projects/__main__.py, utils/__main__.py, variation/__main__.py
Docstring in `module/__main__.py` is used to show help text when invoking `python -m jcvi`.
Ref #70
=> Add one-line description for each `jcvi` module

compara/catalog.py
Sometimes, the `.x` in gene IDs does not refer to isoforms, or the longest transtripts have been selected before using the module, users may want to have the choice to not strip the gene IDs.
```bash
python -m jcvi.compara.catalog ortholog --nostdpf --dbtype=nucl --no_strip_names Gma Mtr
```
=> add option: --no_strip_names for ortholog (compara/catalog.py)

jcvi/annotation/train.py
In the origin scripts, the gff and fasta should under the working directory, I use os.path.abspath to get the absolute path so that the gff and fasta file could be in any place
=> use abspath instead of relative path

jcvi/compara/catalog.py
jcvi.utils.cbook.py:
`def gene_name(st, exclude=("ev",), sep=".")`
=> added option names to avoid ambiguity

jcvi/graphics/glyph.py, jcvi/graphics/synteny.py
Add option `--glyphstyle arrow` in addition to the rectangle glyph (default)
=> Add alternative style for gene glyphs (#256, thanks @Tong-Chen)

jcvi/algorithms/tsp.py
concorde wrapper broken from py2 to py3
- `sorted()` on heterogeneous set is not removed with no side effect
- `fp.next()` => `next(fp)`
=> [algorithms] Fix bug in tsp from py2 to py3 (#265, thanks @gordonyounkin)

jcvi/annotation/stats.py
If there are many GFF under a same directory and we run `python -m jcvi.annotation.stats genestats`  for each of them, we will get unexpected result because the origin code will generate one "transcript.sizes" file to different GFF file. So It is better to generate "transcript.sizes" with the filename of GFF as prefix to avoid this problem.
If the gff file have a rRNA as feature, some gene will not have mRNA as feature.
If the gff don't have have exon as feature, the num_exons is zero .
=> Update of stats.py

docker/jcvi.dockerfile
Even with -y option on apt-get installs, certain libraries (libxml2-dev) will
prompt for locale info (tzdata) causing hang during build. Setting debian_frontend as
non interactive with ARG rather than ENV changes the behavior during the build
only.
=> Set ubuntu base to non-interactive during image build

jcvi/apps/base.py
base.py "download" function checks if fetch request already exists and skips download if true.
"success" flag remains false so that at line 1453, file shredder is invoked. Missing directory file
then causes subsequent fetch request (e.g. species fetch) to fail.
What we observe is that any initial request works, signon success, directory listing download success.
Subsequent fetch (of directory or species) then fails due to above, then cookies and directory are
deleted. Next fetch requires signon again and succeeds, next one fails, etc.
=> Set "success" flag to True in base.py if file exists to avoid shredding

jcvi/compara/synteny.py, jcvi/graphics/base.py, jcvi/graphics/glyph.py, jcvi/graphics/synteny.py
We abstracted the color palette using separated classes
- `OrientationPalette` plots gene colors based on orientation
- `OrthogroupPalette` plots gene colors based on given orthogroups from blocks file
---
The following section is added to wiki.
Sometimes we want to match the colors of the genes with respect to their homology as indicated in the `blocks` file.
$ python -m jcvi.graphics.synteny blocks grape_peach.bed blocks.layout --glyphcolor=orthogroup
=> Allow glyphcolor to be specified according to a palette

jcvi/annotation/evm.py, jcvi/apps/bowtie.py, jcvi/apps/grid.py, jcvi/assembly/ca.py, jcvi/assembly/opticalmap.py, jcvi/assembly/patch.py, jcvi/formats/vcf.py, jcvi/graphics/align.py, jcvi/graphics/heatmap.py, jcvi/graphics/whisker.py, jcvi/projects/tgbs.py, jcvi/variation/delly.py
We failed to convert all instances of `.next()` to `next()` during our Python 2 to Python 3 upgrade, which lead to #363.
Converted residual instances that we could find. Also drive-by fixed an issue where `Queue()` did not work properly on macOS.
=> Fix py2=>py3: fp.next() converted to next(fp) (thanks @agroppi, #363)

jcvi/compara/synteny.py, jcvi/graphics/base.py, tests/graphics/test_base.py
Latex doesn't work well with certain input characters, like '_', so we need to sanitize strings in `compara.synteny.depth()`.
=> Sanitize display strings with latex() (thanks @goeckeritz, #21)

jcvi/compara/catalog.py, tests/compara/test_synteny.py
Correctly handle relative path in argument, per #389
=> Use op.basename when inferring blastfile prefix

jcvi/assembly/allmaps.py
This is a regression introduced when we migrated from py2 to py3. `zip()` is an iterator object in py3 vs a list in py2. So in this particular case when `FLIP` configuration is written, the iterator is no longer valid, leaving an empty list. Fixed by converting to an actual list instead.
=> Fix issue when writing "FLIP" in tour (thanks @jguppy, #456)

jcvi/formats/gff.py
Updates to jcvi.formats.gff load. 
Added a 'downstream' option for feature extraction which mirrors the functionality of 'upstream'. Using the downstream option will extract sequences downstream of the default feature (i.e. mRNA). Options for extracting downstream sequences include 'TES' (transcriptional end site) and 'TrSS' (translational end site), which mirror the functionality of 'TSS' and 'TrSS' for the upstream option.
An option named avoidFeatures was added which impacts the function of both 'upstream' and 'downstream'. If avoidFeatures is specified, up- or downstream sequences with a maximum length provided by 'feature' will be extracted such that they do not overlap with neighboring annotations. If the start/end coordinates of an mRNA feature overlaps with a neighbor gene in the …
=> Gff load avoid features

jcvi/apps/base.py, jcvi/apps/ks.py, jcvi/graphics/base.py, jcvi/graphics/chromosome.py, jcvi/graphics/dotplot.py, jcvi/graphics/karyotype.py, jcvi/graphics/synteny.py
Some plots (`karyotype`, `chromosome`, `ks`, `synteny`) randomly assign colors when not specified.
This PR adds a `--seed` so that we can get stable colors for pubs.
=> Add --seed in graphics options

jcvi/algorithms/lpsolve.py, jcvi/algorithms/tsp.py, jcvi/annotation/automaton.py, jcvi/annotation/evm.py, jcvi/annotation/reformat.py, jcvi/apps/base.py, jcvi/apps/bwa.py, jcvi/apps/emboss.py, jcvi/apps/fetch.py, jcvi/apps/uclust.py, jcvi/assembly/allmaps.py, jcvi/assembly/patch.py, jcvi/assembly/preprocess.py, jcvi/assembly/sim.py, jcvi/compara/synteny.py, jcvi/formats/base.py, jcvi/formats/genbank.py, jcvi/projects/heterosis.py, jcvi/projects/str.py, jcvi/variation/cnv.py, tests/apps/test_base.py
`FileShredder` is obsoleted by the use of `cleanup`. Just route all instances as well as `shutil.rmtree` to `cleanup`.
=> Remove file shredder

jcvi/graphics/chromosome.py, jcvi/graphics/glyph.py, jcvi/graphics/karyotype.py, jcvi/projects/napus.py
Add option `--chrstyle` to `karyotype` command. Example:
Note chr10 is changed to rectangle since it is too small to draw rounded caps.
=> Add option --chrstyle to karyotype

jcvi/apps/align.py, jcvi/apps/base.py, jcvi/graphics/base.py
Modified `jcvi.apps.base sh()` function to make cmd line calls with `subprocess.check_output()` instead of `subprocess.check_call()`.
check_output() waits until all output is read before it returns, so we can collect msg sent to stderr. It should otherwise behave the same as check_call().
Also added arg `redirect_error` to `sh()`, setting this to `subprocess.STDOUT` collects the error in the `.output` attribute of any error returned by `check_output`.
Modified calls to `lastal` in `jcvi.apps.align last()` to use this new error logging behaviour.
Modified `jcvi.graphics.base savefig()` to not attempt to re-save after  doing a `rc("text", usetex=False)`, this never worked anyway. Instead log suggestion to use `--notex` option.
=> Improve error logging for external tools

jcvi/apps/align.py, jcvi/apps/base.py, jcvi/graphics/base.py
1) Log specific cases where latex use is disabled.
- latex or lp not on path
- '--notex' is on
2) If savefig() fails an empty pdf may be created and successful save msg is displayed.
- Check for empty file and remove
- Exit with error is savefig fails
=> Latex availability logging and error handling update

jcvi/compara/catalog.py
When parameter `--ignore_zero_anchor` is specified, if there is no anchor between two species, a warning message instead of an error exit would be caused.
Sorry for the formatting problems and these have been reverted.
=> add ignore zero anchor parameter for skip no matches in batch search

jcvi/graphics/synteny.py
Adding option `--noprune` to `jcvi.graphics.synteny` module. 
If set, small features in annotation track will not be excluded.
Please test before merging.
closes #623
=> Add --noprune opt to retain small features in microsynteny plots.

README.md, build.py, pyproject.toml, src/jcvi/__init__.py
- Remove `.so` from source tarball
- Name `.whl` with platform specific tag
- On linux, manually tested with `pip install` on both source tarball and wheel
One caveat, I may have to install `hatchling`, `hatch-vcs`, or `hatch` despite them being in `[build-system]`.
I am not sure if the standalone tarball and wheel, once hosted on PyPI, will be able to trigger installing the dependencies first  on the client machine.
=> Fix dists linux
